-- Generated by orbit from THEORY.md example

function foo()
  local bar = 1
  return bar
end


function baz()
  local bax = false
  return bax
end


function luaFoo()
  local luaBar = true
  return luaBar
end
extern = {}

extern["fstat_INODE64"] = function() end

