-- Generated by orbit from THEORY.md example

extern = {}

function foo()
  local bar = 1
  return bar
end


extern = {}

function baz()
  local bax = false
  return bax
end


function luaFoo()
  local luaBar = true
  return luaBar
end
extern["fstat_INODE64"] = function() end

