const std = @import("std");
const orbit = @import("orbit.zig");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var lvm = try orbit.Lvm.init(&alloc, .{});
    defer lvm.deinit();

    // Test case 1: Simple function
    const foo_code = "pub fn foo() { const bar: i32 = 1; return bar; }";

    const foo_lua = try lvm.build(foo_code);
    defer alloc.free(foo_lua);

    // Write the generated Lua to orb_theory.lua
    const output_file = try std.fs.cwd().createFile("orb_theory.lua", .{});
    defer output_file.close();
    try output_file.writeAll("-- Generated by orbit from THEORY.md example\n\n");
    try output_file.writeAll(foo_lua);

    std.debug.print("Generated orb_theory.lua\n", .{});

    // Test case 2: Parse inline Zig code
    const baz_code = "pub fn baz() { const bax: bool = false; return bax; }";

    const baz_lua = try lvm.parse(baz_code);
    defer alloc.free(baz_lua);

    const append_file = try std.fs.cwd().openFile("orb_theory.lua", .{ .mode = .read_write });
    defer append_file.close();
    try append_file.seekFromEnd(0);
    try append_file.writeAll("\n");
    try append_file.writeAll(baz_lua);

    std.debug.print("Appended baz() to orb_theory.lua\n", .{});

    // Test case 3: Raw Lua passthrough
    const raw_lua =
        \\function luaFoo()
        \\  local luaBar = true
        \\  return luaBar
        \\end
    ;

    const lua_result = try lvm.lua(raw_lua);

    const append_file2 = try std.fs.cwd().openFile("orb_theory.lua", .{ .mode = .read_write });
    defer append_file2.close();
    try append_file2.seekFromEnd(0);
    try append_file2.writeAll("\n");
    try append_file2.writeAll(lua_result);

    std.debug.print("Appended raw Lua to orb_theory.lua\n", .{});

    // Test case 4: Extern declaration
    const extern_code = "pub extern fn fstat_INODE64();";

    const extern_lua = try lvm.build(extern_code);
    defer alloc.free(extern_lua);

    const append_file3 = try std.fs.cwd().openFile("orb_theory.lua", .{ .mode = .read_write });
    defer append_file3.close();
    try append_file3.seekFromEnd(0);
    try append_file3.writeAll("\n");
    try append_file3.writeAll(extern_lua);

    std.debug.print("Appended extern declaration to orb_theory.lua\n", .{});

    std.debug.print("Test completed successfully!\n", .{});
}
